site_name: Srijan Dev Guidelines
pages:
- Home: index.md
- Git Workflow: git.md
- Using Features Module: 'drupal/features_module.md'
- CSS: css.md
- JavaScript: javascript.md
- Templating: templating.md
- SiteAudit: 'drupal/drupal_standards.md'
- drupalStandards: 'drupal/drupal_standards.md'
theme: readthedocs
