site_name: Srijan Dev Guidelines
pages:
- Home: index.md
- Git Workflow: git.md
- Using Features Module: features_module.md
- CSS: css.md
- JavaScript: javascript.md
- Templating: templating.md
- SiteAudit: drupal_standards.md
- DrupalStandards: drupal_standards.md
theme: readthedocs
