site_name: Srijan Dev Guidelines
pages:
- Home: index.md
- Git Workflow: git.md
- Using Features Module: features_module.md
- CSS: css.md
- JavaScript: javascript.md
- Templating: templating.md  
theme: readthedocs
